-- hify database schema (PostgreSQL 18)
--
-- Conventions per CLAUDE.md:
--   names lower_snake_case; PK `id` bigint identity; created_at/updated_at
--   timestamp (auto-filled by the application, DB default as a fallback);
--   logical delete `deleted` smallint (0 = normal, 1 = deleted);
--   NO database-level foreign keys (maintained in the app layer).
--
-- Apply manually (assumes database `hify` exists; run once if not):
--   CREATE DATABASE hify;
--   psql -U postgres -d hify -f hify-app/src/main/resources/db/schema.sql
--
-- The file is idempotent (IF NOT EXISTS); after altering a table manually,
-- DROP it first or it will silently keep the old definition.
--
-- Column notes are plain SQL comments: PostgreSQL has no inline COMMENT
-- clause, table comments use COMMENT ON TABLE below.

-- ---------------------------------------------------------------------------
-- provider: a model-provider access instance (one protocol + one credential set)
-- auth_config structure depends on `type`:
--   OPENAI / OPENAI_COMPATIBLE -> { "apiKey": "sk-..." }   (Bearer)
--   ANTHROPIC                 -> { "apiKey": "sk-ant-..." } (x-api-key header)
--   OLLAMA                    -> null (no auth)
-- Future types may carry { clientId, clientSecret, tokenUrl, ... } etc.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS provider (
  id          BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name        VARCHAR(100) NOT NULL,  -- 供应商名称，唯一
  type        VARCHAR(30)  NOT NULL,  -- OPENAI / ANTHROPIC / DEEPSEEK / OLLAMA / OPENAI_COMPATIBLE
  base_url    VARCHAR(500) NOT NULL,  -- API 基础地址
  auth_config JSONB,                  -- 鉴权配置，结构按 type 不同
  description VARCHAR(255),           -- 备注
  enabled     BOOLEAN      NOT NULL DEFAULT TRUE,
  created_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted     SMALLINT     NOT NULL DEFAULT 0
);
COMMENT ON TABLE provider IS '模型提供商';
CREATE UNIQUE INDEX IF NOT EXISTS uk_provider_name ON provider (name);

-- ---------------------------------------------------------------------------
-- model_config: models exposed by one provider access instance (N:1)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS model_config (
  id           BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  provider_id  BIGINT       NOT NULL,  -- 所属供应商 ID，provider.id（应用层外键）
  name         VARCHAR(100) NOT NULL,  -- 展示名，如 GPT-4o
  model_id     VARCHAR(100) NOT NULL,  -- 调用时传给 API 的值
  context_size INT,                    -- 上下文窗口大小（token 数）
  extra_params JSONB,                  -- 模型级别扩展参数
  enabled      BOOLEAN      NOT NULL DEFAULT TRUE,
  created_at   TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at   TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted      SMALLINT     NOT NULL DEFAULT 0
);
COMMENT ON TABLE model_config IS '模型配置';
CREATE INDEX IF NOT EXISTS idx_model_config_provider_id ON model_config (provider_id);

-- ---------------------------------------------------------------------------
-- provider_health: 1:1 probe results per provider. High write frequency, kept
-- out of the provider row so it never invalidates the provider cache.
-- No logical delete: one row per provider, upsert semantics.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS provider_health (
  id              BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  provider_id     BIGINT       NOT NULL,  -- 供应商 ID，唯一
  status          VARCHAR(20)  NOT NULL DEFAULT 'UNKNOWN',  -- UP / DOWN / DEGRADED / UNKNOWN
  last_check_at   TIMESTAMP,              -- 最后探测时间
  last_success_at TIMESTAMP,              -- 最后成功时间
  fail_count      INT          NOT NULL DEFAULT 0,  -- 连续失败次数
  latency_ms      INT,                    -- 最近一次延迟 ms
  error_message   VARCHAR(500),           -- 最近失败原因
  updated_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);
COMMENT ON TABLE provider_health IS '供应商健康状态';
CREATE UNIQUE INDEX IF NOT EXISTS idx_provider_health_provider_id ON provider_health (provider_id);

-- ---------------------------------------------------------------------------
-- agent: agent definition (model binding + system prompt; MCP tools via agent_tool)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS agent (
  id                BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name              VARCHAR(128) NOT NULL,  -- Agent name shown in the console
  description       VARCHAR(512),
  system_prompt     TEXT,                   -- System prompt defining agent behavior
  model_config_id   BIGINT       NOT NULL,  -- Bound model, model_config.id (app-layer FK)
  temperature       DOUBLE PRECISION,       -- NULL = provider default
  max_tokens        INT,                    -- NULL = provider default
  max_context_turns INT          NOT NULL DEFAULT 10,  -- 保留最近几轮上下文
  enabled           BOOLEAN      NOT NULL DEFAULT TRUE,
  created_at        TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at        TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted           SMALLINT     NOT NULL DEFAULT 0
);
COMMENT ON TABLE agent IS 'Agent configurations';
CREATE INDEX IF NOT EXISTS idx_agent_model_config_id ON agent (model_config_id);

-- ---------------------------------------------------------------------------
-- mcp_server: an MCP server exposing tools callable by agents
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS mcp_server (
  id          BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name        VARCHAR(128) NOT NULL,
  description VARCHAR(255),
  transport   VARCHAR(16)  NOT NULL,  -- Transport type: stdio | sse
  command     VARCHAR(255),           -- For stdio: command to launch
  args        JSONB,                  -- For stdio: launch arguments as a JSON array
  url         VARCHAR(512),           -- For sse: MCP endpoint URL
  created_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted     SMALLINT     NOT NULL DEFAULT 0
);
COMMENT ON TABLE mcp_server IS 'MCP servers';
CREATE UNIQUE INDEX IF NOT EXISTS uk_mcp_server_name ON mcp_server (name);

-- ---------------------------------------------------------------------------
-- agent_tool: M:N binding between agents and MCP servers
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS agent_tool (
  id         BIGINT    GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  agent_id   BIGINT    NOT NULL,  -- agent.id (app-layer FK)
  tool_id    BIGINT    NOT NULL,  -- 关联 mcp_server.id
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted    SMALLINT  NOT NULL DEFAULT 0
);
COMMENT ON TABLE agent_tool IS 'Agent to MCP server bindings';
CREATE UNIQUE INDEX IF NOT EXISTS uk_agent_tool ON agent_tool (agent_id, tool_id);

-- ---------------------------------------------------------------------------
-- chat_session: one conversation with an agent
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS chat_session (
  id                   BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  agent_id             BIGINT       NOT NULL,  -- agent.id (app-layer FK)
  title                VARCHAR(128),           -- Derived from the first user message
  status               VARCHAR(20)  NOT NULL DEFAULT 'ACTIVE',  -- ACTIVE / ARCHIVED
  last_message_at      TIMESTAMP,              -- Last activity, for list ordering
  message_count        INT          NOT NULL DEFAULT 0,
  last_message_preview VARCHAR(64),            -- Excerpt of the newest message, for the session list
  created_at           TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at           TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted              SMALLINT     NOT NULL DEFAULT 0
);
COMMENT ON TABLE chat_session IS 'Chat sessions';
CREATE INDEX IF NOT EXISTS idx_chat_session_agent_id ON chat_session (agent_id);
CREATE INDEX IF NOT EXISTS idx_chat_session_last_message_at ON chat_session (last_message_at);

-- ---------------------------------------------------------------------------
-- chat_message: a single message in a session (fastest growing table)
--
-- NO logical delete on purpose: rows are physically removed together with
-- their session (session delete -> DELETE WHERE session_id). A `deleted`
-- column would force `WHERE deleted = 0` onto every read of the hottest table
-- and widen the (session_id, id) index. Precedent: provider_health.
--
-- status state machine (streaming writes a placeholder first):
--   user      -> COMPLETED immediately
--   assistant -> GENERATING, then COMPLETED (content + usage) or FAILED
--                (content keeps whatever deltas were already produced)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS chat_message (
  id                BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_id        BIGINT      NOT NULL,  -- chat_session.id (app-layer FK)
  parent_id         BIGINT,                -- Message being replied to; NULL = first message
  role              VARCHAR(16) NOT NULL,  -- user | assistant | system | tool
  content           TEXT        NOT NULL,  -- Message text
  status            VARCHAR(16) NOT NULL DEFAULT 'COMPLETED',  -- GENERATING / COMPLETED / FAILED
  finish_reason     VARCHAR(32),           -- stop | length | tool_calls | cancelled | ...
  prompt_tokens     INT         NOT NULL DEFAULT 0,
  completion_tokens INT         NOT NULL DEFAULT 0,
  meta              JSONB,                 -- tool_calls / tool_call_id / RAG citations
  created_at        TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at        TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP
);
COMMENT ON TABLE chat_message IS 'Chat messages';
CREATE INDEX IF NOT EXISTS idx_chat_message_session_id_id ON chat_message (session_id, id);
CREATE INDEX IF NOT EXISTS idx_chat_message_parent_id ON chat_message (parent_id);

-- ---------------------------------------------------------------------------
-- demo_item: CRUD scaffold demo (remove once real business entities land)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS demo_item (
  id         BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name       VARCHAR(128) NOT NULL,
  status     INT          NOT NULL,
  created_at TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted    SMALLINT     NOT NULL DEFAULT 0
);
COMMENT ON TABLE demo_item IS 'Demo CRUD entity';
