-- pgvector 最小示例：安装完扩展后，从建表到相似度查询一气跑通
--
-- 运行：psql -h localhost -U postgres -d hify -f docs/pgvector-demo.sql
--
-- 表名用 document_chunk（knowledge 模块的真实表名），但这里为了讲清楚
-- 只保留三列；正式建表时会再加 document_id、chunk_index 等字段。
-- 注意向量维度：示例用 3 维便于肉眼理解，真实场景必须等于 embedding
-- 模型的输出维度（OpenAI text-embedding-3-small = 1536，bge-m3 = 1024），
-- 维度定错了插不进去——届时 DROP 重建即可。

-- ① 启用扩展（每个数据库一次；需要超级用户）
CREATE EXTENSION IF NOT EXISTS vector;

-- ② 建表
DROP TABLE IF EXISTS document_chunk;
CREATE TABLE document_chunk (
  id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  content   TEXT NOT NULL,
  embedding vector(3)
);

-- ③ 插入：向量以字符串形式给出
INSERT INTO document_chunk (content, embedding) VALUES
  ('猫是一种小型哺乳动物', '[0.9, 0.1, 0.2]'),
  ('狗是人类忠实的朋友',   '[0.8, 0.2, 0.1]'),
  ('红烧肉的家常做法',     '[0.1, 0.9, 0.8]'),
  ('糖醋排骨怎么做',       '[0.2, 0.8, 0.9]');

-- ④ 相似度查询
--    <=> 是余弦距离（0 = 完全相同，2 = 完全相反），越小越相似；
--    "1 - 距离" 换算成人能读的相似度分数。
--    查询向量 [0.85, 0.15, 0.15] 位于"猫/狗"那一簇附近。
SELECT
  content,
  ROUND((1 - (embedding <=> '[0.85, 0.15, 0.15]'))::numeric, 4) AS similarity
FROM document_chunk
ORDER BY embedding <=> '[0.85, 0.15, 0.15]'
LIMIT 3;

-- ⑤ 索引（几万条以内顺序扫描也够快，数据涨上来再加）
--    HNSW：查询快、构建慢、吃内存，是目前的首选
--    IVFFlat：构建快、内存小，但需要表里先有数据才能建得准
CREATE INDEX IF NOT EXISTS idx_document_chunk_embedding
  ON document_chunk USING hnsw (embedding vector_cosine_ops);

-- 附：三种距离操作符（索引的 opclass 必须和查询用的操作符对应）
--   <=>  vector_cosine_ops       余弦距离（文本 embedding 最常用）
--   <->  vector_l2_ops           L2 欧氏距离
--   <#>  vector_ip_ops           负内积（越大越相似，注意是负的）
